# Generated by Django 4.1 on 2022-08-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_profile_avatar_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=None, upload_to='profile_images'),
        ),
    ]
